"""
SIREN Report Exporter
======================
Exports IncidentReport objects to Markdown and JSON formats.
Markdown output follows professional incident report formatting
suitable for stakeholder communication and archival.
"""

import json
from src.report_engine import IncidentReport


class ReportExporter:
    """Handles exporting an IncidentReport to various formats."""

    def __init__(self, report: IncidentReport):
        self.report = report

    # ------------------------------------------------------------------
    # Markdown export
    # ------------------------------------------------------------------

    def to_markdown(self) -> str:
        """
        Generate a professional Markdown incident report.

        Sections follow the NIST 800-61 incident handling lifecycle:
        Preparation → Detection → Containment → Eradication → Recovery → Lessons Learned
        """
        r = self.report
        score_data = r.calculate_severity_score()
        severity_badge = self._severity_badge(r.severity)

        lines = []
        lines.append(f"# 🚨 Incident Report: {r.title}")
        lines.append("")
        lines.append(f"**Incident ID:** `{r.incident_id}`  ")
        lines.append(f"**Generated:** {r.created_at}  ")
        lines.append(f"**Generated by:** SIREN v1.0.0")
        lines.append("")
        lines.append("---")
        lines.append("")

        # ── Metadata ──────────────────────────────────────────────────
        lines.append("## 📋 Incident Metadata")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| **Severity** | {severity_badge} {r.severity} |")
        lines.append(f"| **Category** | {r.category} |")
        lines.append(f"| **Analyst** | {r.analyst} |")
        lines.append(f"| **Severity Score** | {score_data['score']}/10 ({score_data['rating']}) |")
        lines.append(f"| **Detection Date** | {r.detection_date or 'N/A'} |")
        lines.append(f"| **Containment Date** | {r.containment_date or 'N/A'} |")
        lines.append(f"| **Eradication Date** | {r.eradication_date or 'N/A'} |")
        lines.append(f"| **Recovery Date** | {r.recovery_date or 'N/A'} |")
        lines.append("")

        if r.description:
            lines.append(f"**Description:** {r.description}")
            lines.append("")

        # ── Executive Summary ─────────────────────────────────────────
        if r.executive_summary:
            lines.append("---")
            lines.append("")
            lines.append("## 📝 Executive Summary")
            lines.append("")
            lines.append(r.executive_summary)
            lines.append("")

        # ── Timeline ──────────────────────────────────────────────────
        if r.timeline_events:
            lines.append("---")
            lines.append("")
            lines.append("## 🕐 Incident Timeline")
            lines.append("")
            lines.append("| # | Timestamp | Event | Source |")
            lines.append("|---|-----------|-------|--------|")
            for idx, event in enumerate(r.timeline_events, 1):
                source = event.source if event.source else "—"
                lines.append(
                    f"| {idx} | `{event.timestamp}` | {event.description} | {source} |"
                )
            lines.append("")

        # ── IOCs ──────────────────────────────────────────────────────
        if r.iocs:
            lines.append("---")
            lines.append("")
            lines.append("## 🔍 Indicators of Compromise (IOCs)")
            lines.append("")
            lines.append("| # | Type | Value | Context |")
            lines.append("|---|------|-------|---------|")
            for idx, ioc in enumerate(r.iocs, 1):
                context = ioc.context if ioc.context else "—"
                lines.append(
                    f"| {idx} | {ioc.ioc_type} | `{ioc.value}` | {context} |"
                )
            lines.append("")

        # ── Affected Systems ──────────────────────────────────────────
        if r.affected_systems:
            lines.append("---")
            lines.append("")
            lines.append("## 💻 Affected Systems")
            lines.append("")
            lines.append("| # | Hostname | IP Address | Impact |")
            lines.append("|---|----------|------------|--------|")
            for idx, sys in enumerate(r.affected_systems, 1):
                impact = sys.impact if sys.impact else "—"
                lines.append(
                    f"| {idx} | `{sys.hostname}` | `{sys.ip_address}` | {impact} |"
                )
            lines.append("")

        # ── Severity Score Breakdown ──────────────────────────────────
        lines.append("---")
        lines.append("")
        lines.append("## 📊 Severity Score Breakdown")
        lines.append("")
        lines.append(f"| Factor | Score |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Base Severity | {score_data['breakdown']['base_severity']} |")
        lines.append(f"| IOC Factor (+0.5/IOC, max 3) | {score_data['breakdown']['ioc_factor']} |")
        lines.append(f"| System Factor (+0.75/system, max 3) | {score_data['breakdown']['system_factor']} |")
        lines.append(f"| Critical Bonus | {score_data['breakdown']['critical_bonus']} |")
        lines.append(f"| **Total** | **{score_data['score']}/10 ({score_data['rating']})** |")
        lines.append("")

        # ── Recommendations ───────────────────────────────────────────
        if r.recommendations:
            lines.append("---")
            lines.append("")
            lines.append("## ✅ Recommendations")
            lines.append("")
            for idx, rec in enumerate(r.recommendations, 1):
                lines.append(f"{idx}. {rec}")
            lines.append("")

        # ── Footer ────────────────────────────────────────────────────
        lines.append("---")
        lines.append("")
        lines.append(
            "*Report generated by [SIREN](https://github.com/Rootless-Ghost/SIREN) "
            "— Security Incident Response Engine & Notation*"
        )

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # JSON export
    # ------------------------------------------------------------------

    def to_json(self) -> str:
        """Serialize the report to a formatted JSON string."""
        return json.dumps(self.report.to_dict(), indent=2, ensure_ascii=False)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _severity_badge(severity: str) -> str:
        """Return an emoji badge for the severity level."""
        badges = {
            "Low": "🟢",
            "Medium": "🟡",
            "High": "🟠",
            "Critical": "🔴",
        }
        return badges.get(severity, "⚪")
